---
# Change local user's password
#
# Example
#            {
#                name = "Win_User_Password"
#                value = [ {name = "LocalUser1", password = "Welcome123"} ]
#            },
#
# Legacy DEPRECATED syntax
#                {name = "LocalUser1", value = "Welcome123"}
# password.yml
- win_user:
    name: "{{ item.name }}"
    # Keep backward compatibility with deprecated syntax
    password: "{{ item.value | default(item.password) }}"
    state: present