---
# Upgrades debian-based systems to the latest version.
#
# Example usage:
#        features    = [ "Linux_Apt_Package_Upgrade" ]
# Ansible apt is slightly broken in Kali. Using manual installation instead
#- name: Upgrade all packages to latest version
#  apt:
#    upgrade: dist
#    update_cache: yes
#    dpkg_options: 'force-confold,force-confdef'

- name: Upgrade system. Please be patient (~30min)...
  shell: |
    sudo apt update
    sudo DEBIAN_FRONTEND=noninteractive APT_LISTCHANGES_FRONTEND=none apt dist-upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew"
    sudo DEBIAN_FRONTEND=noninteractive APT_LISTCHANGES_FRONTEND=none apt dist-upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew"
            
- name: Reboot if requested by the system
  shell: sleep 10 && sudo /sbin/shutdown -r now 'Rebooting box to update system libs/kernel as needed'
  args:
   removes: /var/run/reboot-required
  async: 300
  poll: 0
  ignore_errors: true
 
- name: Wait for system to become reachable again
  wait_for_connection:
    delay: 60
    timeout: 300