---
# PrincipalsAllowedToRetrieveManagedPassword.yml
- win_shell: |
    $password = ConvertTo-SecureString "{{ansible_password}}" -AsPlainText -Force
    $cred = New-Object System.Management.Automation.PSCredential("{{ansible_user}}", $password)
    if ("{{ item.value }}") {
        Set-ADServiceAccount -Credential $cred -Identity "{{ item.name }}" -PrincipalsAllowedToRetrieveManagedPassword "{{ item.value }}"
    } else {
        Set-ADServiceAccount -Credential $cred -Identity "{{ item.name }}" -PrincipalsAllowedToRetrieveManagedPassword "$(hostname)$"
    }